### ISSUE TITLE
File association and form format

### ISSUE THREAD

**Issue by blackbart420** [zerokol/vscode-eex-beautify#1]
Hello, 
thank you for this extension !

for me the association 
"*.eex": "eex"
does not work.

But this work fine : 

    "files.associations": {
        "*.eex": "HTML (Eex)"
    },

Also I have a question. There is no indentation after a form tag, for instance : 

```
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
<div>
  <%= text_input f, :name, placeholder: "Name" %>
</div>
<%= submit "Create User" %>
<% end %>
```

I think it should be indented this way, isn't it ?

```
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
  <div>
    <%= text_input f, :name, placeholder: "Name" %>
  </div>
  <%= submit "Create User" %>
<% end %>
```

**Comment by shijithkjayan** [comment]
for me the association "*.eex": "eex" formats the document. But then there will be no colouring for the code. Everything will be white

**Comment by chrisallenmoore** [comment]
> for me the association "*.eex": "eex" formats the document. But then there will be no colouring for the code. Everything will be white

I find the same thing. @shijithkjayan did you ever get syntax coloring while being able to format?

**Comment by shijithkjayan** [comment]
@chrisallenmoore no. 
It would be very helpful if someone can find a solution to this

**Comment by fschoenfeldt** [comment]
Too bad https://github.com/zerokol/vscode-eex-beautify/pull/5 was ignored by the maintainer, this makes formatting elixir `.eex` & `.leex` templates basically impossible for me.

**Comment by fschoenfeldt** [comment]
Maybe you can send this patch to https://github.com/RoyalMist/vscode-eex-format ? It's a fork that seem to be actively maintained and seems to have the same issue.

There's also https://github.com/ouven/vscode-yab-for-eex-leex btw.

**Comment by alvesoaj** [comment]
Let me check
